apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: health-probes-sts
  namespace: testenv
  labels:
    app: health-probes-sts
spec:
  selector:
    matchLabels:
      app: health-probes
  serviceName: health-probe-svc
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: health-probes
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - health-probes
      restartPolicy: Always
      containers:
        - name: health-probe
          image: health-probes:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: http
          # Use the followint to adjust the default times if you wish
          # env:
          #   - name: WAIT_STARTUP_TIME
          #     value: "0"
          #   - name: WAIT_LIVENESS_TIME
          #     value: "60"
          #   - name: WAIT_READINESS_TIME
          #     value: "90"
          #   - name: JOB_DURATION_TIME
          #     value: "20"
          livenessProbe:
            httpGet:
              path: /livenessProbe
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
            #timeoutSeconds: 1
            #successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /maxReadinessCountProbe
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            #timeoutSeconds: 1
            #successThreshold: 1
            failureThreshold: 2

          # Only in 1.16 and up
          # The startupProbe will precede the liveness and readiness Probes
          #startupProbe:
          #  httpGet:
          #    path: /startupProbe
          #    port: http
            # This means it has a maximum of 30*5=150 seconds to start up before it fails
          #  failureThreshold: 30
          #  periodSeconds: 5
--- 
apiVersion: v1
kind: Service
metadata:
  name: health-probe-svc
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: health-probes
---